# config/inference.yaml
paths:
  scalers: "data/scalers/"
  encoders: "data/encoders/"

model:
  model_1_path: "models/model_7_6_fine_tunning.keras"
  model_2_path: "models/model_7_9_fine_tunning.keras"
  num_groups_extended_model_1: 4 # Poner la clase que corresponda + 1
  threshold_model_1: 0.5164849
  max_class_model_2: 5
